### ISSUE TITLE
Support nested block descriptions

### ISSUE THREAD

**Issue by fleischie** [fleischie/vim-styled-components#3]
CSS only supports one layer of block definitions:

```css
  main {
    article {
      section {
        padding: 25px 50px 0 1rem;
      }
    }
  }
```

Only the `main` is highlighted, the `article` and `section` is merely a string literal.
